hdata <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
hsubdata <- hdata[hdata$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(hsubdata$Date, hsubdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(hsubdata$Global_active_power)
globalReactivePower <- as.numeric(hsubdata$Global_reactive_power)
voltage <- as.numeric(hsubdata$Voltage)
subMetering1 <- as.numeric(hsubdata$Sub_metering_1)
subMetering2 <- as.numeric(hsubdata$Sub_metering_2)
subMetering3 <- as.numeric(hsubdata$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime, globalActivePower, type="l", ylab="Global Active Power", xlab="", cex=0.2)
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, subMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), bty="o")
plot(datetime, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()