hdata <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
hsubdata <- hdata[hdata$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(hsubdata$Date, hsubdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
subMetering1 <- as.numeric(hsubdata$Sub_metering_1)
subMetering2 <- as.numeric(hsubdata$Sub_metering_2)
subMetering3 <- as.numeric(hsubdata$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime, subMetering1, type="l", col="black",ylab="Energy Submetering")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()